name: brookie
channels:
  - conda-forge # pip, python, fastapi, uvicorn, pandas, databases
dependencies:
  - python=3.8
  - fastapi
  - uvicorn
  - pandas
  - databases
  - pip
  - pip:
      - python-libarchive
      - datafiles
