name: brookie
channels:
  - conda-forge # pip, python
dependencies:
  - python=3
  - fastapi
  - uvicorn
  - pandas
  - pip
  - pip:
      - python-libarchive
      - fastapi
      - uvicorn
      - datafiles
      - databases[sqlite]
